package com.neuedu.dao;

import com.neuedu.pojo.Shipping;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shipping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shipping
     *
     * @mbggenerated
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shipping
     *
     * @mbggenerated
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shipping
     *
     * @mbggenerated
     */
    List<Shipping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_shipping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shipping record);

    /**
     * 根据用户Id和地址Id删除地址
     * @param userId
     * @param shippingId
     * @return
     */
    int deleteShippingByUserIdAndShippingId(@Param("userId") Integer userId,@Param("shippingId") Integer shippingId);
    /**
     * 根据参数更新
     */
    int updateShippingByShipping(Shipping shipping);

    /**
     * 根据用户名和地址id查看详细地址
     * @param userId
     * @param shippingId
     * @return
     */
    Shipping selectShippingByUserIdAndShippingId(@Param("userId") Integer userId,@Param("shippingId") Integer shippingId);

    /**
     * 根据用户id查询地址信息
     * @param userId
     * @return
     */
    List<Shipping> selectShippingByUserId(Integer userId);
}